### ISSUE TITLE
Subscription levels with slave subscription support shows “Wrong username” for empty field

### ISSUE THREAD

**Issue by photodude** [akeeba/akeebasubs#96] opened 2015-01-03 18:08 UTC
Subscription levels with slave subscription support intermittently shows warning “Wrong username” for empty field. 
Replication steps
1.	Create new subscription with default settings 30days length, 50 for price, and at least 1 slave
2.	Create menu item for sign up [Akeeba Subscriptions » All Levels (Awesome layout)]
3.	Start sign up on front end
4.	One first load the “Add-on username” fields with show warning “Wrong username” with the fields being empty
5.	Leave a required field blank and Complete sign up (tested with test payment method)
6.	The “Add-on username” fields will again show warning “Wrong username” with the field being empty
7.	Complete sign up with all required fields completed (tested with test payment method)
8.	Select VIEW DETAILS from “my subscriptions” menu item
9.	The “Add-on username” fields will sometimes show warning “Wrong username” with the field being empty
10.	Select Update subscription details
11.	Select renew subscription from “my subscriptions” menu item
12.	The “Add-on username” fields will sometimes show warning “Wrong username” with the fields are empty (seems more common when there are 10 slaves (Add-on username which are empty)
13.	Issue seems more common on first load or if the browser window is closed then restored from history/recent closed list

**Comment by nikosdion** [comment] 2015-01-04 00:22
This is by design of the validation infrastructure. Changing it is nigh impossible without breaking much more important features such as tax display. Considering that breaking tax display violates the law in most (all?) EU member states and carries hefty fines I think I prefer the occasionally wrong validation label for add-on usernames. Closing as "won't fix".

**Closed by nikosdion** 2015-01-04 00:22 UTC
Labels: wontfix
